### ISSUE TITLE
Query page

### ISSUE THREAD

**Issue by martinlindhe** [addwiki/guzzle-mediawiki-client#2]
Hello. I'm trying to use this client to get the article data from a mediawiki page.

However, the result dont even contain the content. Maybe i am doing something wrong?

I'm trying to tell the client to perform the following:
https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&format=json&titles=Monkey%20wrench&rvlimit=1

```
        $cli =  MediawikiApiClient::factory([
            'base_url' => 'https://en.wikipedia.org/w/api.php',
        ]);

        $res = $cli->query([
            'prop' => 'revisions',
            'rvprop' => 'content',
            'format' => 'json',
            'titles' => 'Monkey wrench',
        ]);
```

the output differs from what you get if you follow the above url, more specifically that the 'revisions' dont contain any of the data as seen by using the above api request

```
"revisions":[{"contentformat":"text/x-wiki","contentmodel":"wikitext","*":"article content"
```

instead the following is returned:

```
array:2 [
  "warnings" => array:1 [
    "query" => array:1 [
      "*" => "Formatting of continuation data will be changing soon. To continue using the current formatting, use the 'rawcontinue' parameter. To begin using the new format, pass an empty string for 'continue' in the initial query."
    ]
  ]
  "query" => array:1 [
    "pages" => array:1 [
      473916 => array:4 [
        "pageid" => 473916
        "ns" => 0
        "title" => "Monkey wrench"
        "revisions" => array:1 [
          0 => array:5 [
            "revid" => 632170673
            "parentid" => 631922367
            "user" => "Shreditor"
            "timestamp" => "2014-11-02T18:34:12Z"
            "comment" => ""
          ]
        ]
      ]
    ]
  ]
]
```

**Comment by addshore** [comment]
The reason your getting the content in the first request you showed is because of

> rvprop=content

If you remove this from the query the content is not displayed and instead you get (revid, parentid, user, timestamp, comment)
What query exactly are you passing in php?

I'm not really actively maintaining this guzzle mediawiki client any more as it is not used in any of my libraries. But it should all remain working!

--------------------------

It might be worth taking a look at https://github.com/addwiki/mediawiki-api and or https://github.com/addwiki/mediawiki-api-base

1) With the **mediawiki-api-base** library you could do something similar to the below (sorry if there are errors I havn't tested this)..

>require_once( __DIR__ . '/vendor/autoload.php' );
>$api = new MediawikiApi( 'http://en.wikipedia.org/w/api.php' );
> $result = $api->getRequest( new SimpleRequest( 'query', array( 'prop' => 'revisions', 'rvprop' => 'content', 'titles' => 'Monkey', 'rvlimit' => 1 ) ) );
> var_dump( $result );

2) The **mediawiki-api** library contains services for using parts of the API. For example you could use the **PageGetter** service instead of the above code https://github.com/addwiki/mediawiki-api/blob/master/src/Service/PageGetter.php#L58

**Comment by martinlindhe** [comment]
Thanks for the pointers.
I'm trying out your mediawiki-api-base from dev-master now

**Comment by martinlindhe** [comment]
With some minor tweaks it is running fine. Thanks!

```
        $api = new MediawikiApi('https://en.wikipedia.org/w/api.php');
        $result = $api->getRequest(new SimpleRequest( 'query', [ 'prop' => 'revisions', 'rvprop' => 'content', 'titles' => $query, 'rvlimit' => 1, 'continue' => '' ] ));


        foreach ($result['query']['pages'] as $pageId => $data) {
            echo $data['title']."\n";
            echo $data['revisions'][0]['*'];
        }
```

**Comment by addshore** [comment]
Awesome, the issue still remains in this repo so I am going to add some deprecation warnings to this repo and point people toward mediawiki-api-base!
